//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class habitacio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public habitacio()
        {
            this.ocupacios = new HashSet<ocupacio>();
        }

        public habitacio(int numero, int metresQuadrats, bool terrassa, bool utilitzable, string titol, string caracteristiques, int codiTipus)
        {
            this.numero = numero;
            this.metresQuadrats = metresQuadrats;
            this.terrassa = terrassa;
            this.utilitzable = utilitzable;
            this.titol = titol;
            this.caracteristiques = caracteristiques;
            this.codiTipus = codiTipus;
        }

        public int numero { get; set; }
        public Nullable<int> metresQuadrats { get; set; }
        public Nullable<bool> terrassa { get; set; }
        public Nullable<bool> utilitzable { get; set; }
        public string titol { get; set; }
        public string caracteristiques { get; set; }
        public Nullable<int> codiTipus { get; set; }
    
        public virtual tipusHabitacio tipusHabitacio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ocupacio> ocupacios { get; set; }
    }
}
