//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class hoste
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hoste()
        {
            this.facturas = new HashSet<factura>();
            this.personas = new HashSet<persona>();
            this.reservas = new HashSet<reserva>();
            this.servei_hoste = new HashSet<servei_hoste>();
            this.ocupacios = new HashSet<ocupacio>();
        }

        public hoste(string dni, string nom, string cognom, string nacionalitat, string telefon, string cp, string poblacio)
        {
            this.dni = dni;
            this.nom = nom;
            this.cognom = cognom;
            this.nacionalitat = nacionalitat;
            this.telefon = telefon;
            this.cp = cp;
            this.poblacio = poblacio;
        }

        public string dni { get; set; }
        public string nom { get; set; }
        public string cognom { get; set; }
        public string nacionalitat { get; set; }
        public string telefon { get; set; }
        public string cp { get; set; }
        public string poblacio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<factura> facturas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<persona> personas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reserva> reservas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<servei_hoste> servei_hoste { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ocupacio> ocupacios { get; set; }
    }
}
