//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class hotelEntities : DbContext
    {
        public hotelEntities()
            : base("name=hotelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<client> clients { get; set; }
        public virtual DbSet<empresa> empresas { get; set; }
        public virtual DbSet<factura> facturas { get; set; }
        public virtual DbSet<habitacio> habitacios { get; set; }
        public virtual DbSet<hoste> hostes { get; set; }
        public virtual DbSet<linia_factura> linia_factura { get; set; }
        public virtual DbSet<ocupacio> ocupacios { get; set; }
        public virtual DbSet<pensio> pensios { get; set; }
        public virtual DbSet<persona> personas { get; set; }
        public virtual DbSet<preu> preus { get; set; }
        public virtual DbSet<reserva> reservas { get; set; }
        public virtual DbSet<servei> serveis { get; set; }
        public virtual DbSet<servei_ocupacio> servei_ocupacio { get; set; }
        public virtual DbSet<temporada> temporadas { get; set; }
        public virtual DbSet<tipusHabitacio> tipusHabitacios { get; set; }
    }
}
