//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class reserva
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public reserva()
        {
            this.hostes = new HashSet<hoste>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> dataInici { get; set; }
        public Nullable<System.DateTime> dataFinal { get; set; }
        public Nullable<decimal> preuTotal { get; set; }
        public Nullable<decimal> bestreta { get; set; }
        public string pensioFk { get; set; }
        public Nullable<int> idClientFk { get; set; }
    
        public virtual client client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hoste> hostes { get; set; }
        public virtual pensio pensio { get; set; }
    }
}
