//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class servei_ocupacio
    {
        public int idOcupacio { get; set; }
        public int idServei { get; set; }
        public Nullable<System.DateTime> data { get; set; }
        public Nullable<decimal> preu { get; set; }

        public servei_ocupacio(int idOcupacio, int idServei, DateTime data, decimal preu)
        {
            this.idOcupacio = idOcupacio;
            this.idServei = idServei;
            this.data = data;
            this.preu = preu;
        }
        public virtual ocupacio ocupacio { get; set; }
        public virtual servei servei { get; set; }
    }
}
