//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class temporada
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public temporada()
        {
            this.preus = new HashSet<preu>();
        }

        public temporada(int codi, string nom, DateTime dataInici, DateTime dataFinal)
        {
            this.codi = codi;
            this.nom = nom;
            this.dataInici = dataInici;
            this.dataFinal = dataFinal;
        }

        public int codi { get; set; }
        public string nom { get; set; }
        public Nullable<System.DateTime> dataInici { get; set; }
        public Nullable<System.DateTime> dataFinal { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<preu> preus { get; set; }
    }
}
